import loginbg from './loginbg.png'
import signOutLogo from './signout.svg'
import contactus from './contactus.png'
import userIcon from './User Icons.svg'
import categoryIcon from './Categories Icon.svg'
import messsagesIcon from './messagesIcon.svg'
import usersIcon from './usersIcon.svg'
import itemsIcon from './itemsIcon.svg'
import categoryIcon2 from './Categories Icon.png'
export {loginbg,signOutLogo,contactus,messsagesIcon,usersIcon,itemsIcon,userIcon,categoryIcon2,categoryIcon}
